name = "probooth-api"
main = "index.js"
compatibility_date = "2024-01-01"

workers_dev = false

[vars]
BUCKET_NAME = "probooth-production"
PUBLIC_CDN_BASE = "https://cdn.polo-booth.com"

[triggers]
crons = ["10 16 * * *"]

[[routes]]
pattern = "api.polo-booth.com"
zone_name = "polo-booth.com"
custom_domain = true

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "probooth-production"

[[kv_namespaces]]
binding = "SESSIONS"
id = "aff08eac47d143b7a8a01dae951e04cb"
